ALTER TABLE projects ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN icon        TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN tags        TEXT NOT NULL DEFAULT '';
